apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubefed-operator
  template:
    metadata:
      labels:
        name: kubefed-operator
    spec:
      serviceAccountName: kubefed-operator
      containers:
        - name: kubefed-operator
          # Replace this with the built image name
<<<<<<< HEAD
          image: quay.io/sohankunkerkar/kubefed-operator:v0.1.0
=======
          image: quay.io/anbhat/kubefed-operator:v0.1.0
>>>>>>> 2c0699ea24d52167ee6738a63c9bfa2fa603e4d8
          command:
          - kubefed-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubefed-operator"
